import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "../components/header/Header";
import Message from "../components/Message";
import OptionMessage from "../components/OptionMessage";
import User from "./components/User";

import "../globals.css";
import "../fontIcons.css";
import LoadingState from "../components/LoadingState";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <User>
          <Header />
          {children}
          <Message />
          <OptionMessage />
          <LoadingState />
        </User>
      </body>
    </html>
  );
}
