name: ci-frontend

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_FRONTEND_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_FROTEND_PROJECT_ID }}

on:
  push:
    branches:
      - main
    paths:
      - "packages/frontend/**"

jobs:
  Cancel_Prev_Workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          workflow_id: "ci-frontend.yml"
          access_token: ${{ github.token }}

  Deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Vercel CLI
        working-directory: packages/frontend
        run: npm i vercel --global --no-audit --no-fund --no-optional
      - name: Pull Vercel Environment
        working-directory: packages/frontend
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Pull the GitHub Environment variables
        working-directory: packages/frontend
        run: |
          echo "NEXT_PUBLIC_SERVER_URI=${{ secrets.SERVER_URI }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_FONTICON_SERVICE_URI=${{ secrets.FONTICON_SERVICE_URI }}" >> $GITHUB_ENV
      - name: Deploy to Vercel
        working-directory: packages/frontend
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
