name: ci-service-fonticons

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_FONTICONS_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_FONTICONS_PROJECT_ID }}

on:
  push:
    branches:
      - main
    paths:
      - "packages/fonticons-service/**"

jobs:
  Cancel_Prev_Workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          workflow_id: 99079597
          access_token: ${{ github.token }}

  Deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Vercel CLI
        working-directory: packages/fonticons-service
        run: npm i vercel --global --no-audit --no-fund --no-optional
      - name: Pull Vercel Environment
        working-directory: packages/fonticons-service
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy to Vercel
        working-directory: packages/fonticons-service
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
